#!/usr/bin/env python3
"""
Refresh the long-lived Instagram access token and write the new value back
into this repo's GitHub Actions secret, so the token never has to be
re-generated by hand.

Instagram long-lived tokens last ~60 days and can be refreshed any time
after the first 24h. This is meant to run on a weekly schedule.

Requires env vars:
  IG_ACCESS_TOKEN   - the current long-lived token (to be refreshed)
  GH_SECRETS_PAT    - a GitHub fine-grained PAT scoped to THIS repo only,
                       with "Secrets: write" repository permission
  GITHUB_REPOSITORY - "owner/repo" (set automatically by GitHub Actions)
"""
import base64
import os
import sys

import requests
from nacl import encoding, public

GRAPH_REFRESH_URL = "https://graph.instagram.com/refresh_access_token"


def refresh_token(current_token: str) -> str:
    resp = requests.get(
        GRAPH_REFRESH_URL,
        params={"grant_type": "ig_refresh_token", "access_token": current_token},
        timeout=30,
    )
    resp.raise_for_status()
    data = resp.json()
    new_token = data["access_token"]
    print(f"Refreshed token; new one expires in {data.get('expires_in')} seconds.")
    return new_token


def encrypt_secret(public_key_b64: str, secret_value: str) -> str:
    public_key = public.PublicKey(public_key_b64.encode("utf-8"), encoding.Base64Encoder())
    sealed_box = public.SealedBox(public_key)
    encrypted = sealed_box.encrypt(secret_value.encode("utf-8"))
    return base64.b64encode(encrypted).decode("utf-8")


def update_github_secret(repo: str, pat: str, secret_name: str, secret_value: str) -> None:
    headers = {
        "Authorization": f"Bearer {pat}",
        "Accept": "application/vnd.github+json",
    }
    key_resp = requests.get(
        f"https://api.github.com/repos/{repo}/actions/secrets/public-key",
        headers=headers,
        timeout=30,
    )
    key_resp.raise_for_status()
    key_data = key_resp.json()

    encrypted_value = encrypt_secret(key_data["key"], secret_value)

    put_resp = requests.put(
        f"https://api.github.com/repos/{repo}/actions/secrets/{secret_name}",
        headers=headers,
        json={"encrypted_value": encrypted_value, "key_id": key_data["key_id"]},
        timeout=30,
    )
    put_resp.raise_for_status()
    print(f"Updated GitHub secret {secret_name}.")


def main() -> int:
    current_token = os.environ.get("IG_ACCESS_TOKEN")
    pat = os.environ.get("GH_SECRETS_PAT")
    repo = os.environ.get("GITHUB_REPOSITORY")
    if not current_token or not pat or not repo:
        print("IG_ACCESS_TOKEN, GH_SECRETS_PAT, and GITHUB_REPOSITORY must be set", file=sys.stderr)
        return 1

    new_token = refresh_token(current_token)
    update_github_secret(repo, pat, "IG_ACCESS_TOKEN", new_token)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
